#!/bin/sh

#
# Copyright (c) 2016 Nicole Cordes

WRITE=true
FILE="ChangeLog"
REFLIST="master..HEAD"

while [ "$1" != "" ]; do
    case $1 in
        -w)
            echo "You are using the deprecated -w option. Changelog is now written by default. You can use --dry-run to prevent writing."
            ;;
        -f|--file)
            shift
            FILE="$1"
            ;;
        --dry-run)
            WRITE=false
            ;;
        *)
            REFLIST="$1"
            ;;
    esac
    shift
done

if `git branch --no-color | grep -q '^\*'`; then
    OUTPUT=""
    HEAD=""
    BRANCH=`git branch --no-color | grep '^\*' | grep -v 'no branch' | sed 's/^* //g' | sed 's/.*\///g' | grep '^[0-9][0-9.]'`
    if [ "$BRANCH" == "" ]; then
        TAGS=`git tag -l`
        if [ "$TAGS" == "" ]; then
            BRANCH="0.1.0"
            REFLIST=""
        else
            COMMIT=`git rev-list --tags --max-count=1`
            BRANCH=`git describe --tags $COMMIT`
            REFLIST="$COMMIT..HEAD"
        fi
    fi
    if [ "$BRANCH" != "" ]; then
        DATE=`date +%Y-%m-%d`
        DIR=${PWD##*/}
        USER=`git config --get user.name`
        HEAD="$DATE         [RELEASE] Release of $DIR $BRANCH ($USER)"$'\n'
    fi

    LOG=`git log --pretty=format:"%ad %h %s (%an)" --date=short --no-merges $REFLIST`
    if [ "$LOG" != "" ]; then
        OUTPUT=$HEAD$LOG;
    fi

    if [ -f $FILE ]; then
        OUTPUT=$OUTPUT$'\n'$'\n'"`cat $FILE`"
    fi

    if $WRITE; then
        echo "$OUTPUT" > $FILE

        OUTPUT=$OUTPUT$'\n'$'\n'"File \"$FILE\" was written."
    fi

    echo "$OUTPUT"

fi
