#!/bin/sh

#
# Copyright (c) 2016 Nicole Cordes

git filter-branch --env-filter 'export GIT_COMMITTER_DATE=$GIT_AUTHOR_DATE; export GIT_COMMITTER_NAME=$GIT_AUTHOR_NAME; export GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL;' $@
git update-ref -d refs/original/refs/heads/master
