#!/bin/sh

#
# Copyright (c) 2016 Nicole Cordes, v1.0.0
#
# This script rewrites the repository information and sets the committer information (date, name, email)
# to the authors information of each commit.
#
#   git rewrite-commitdate [<filter-branch options>] [<number>]
#
#   <filter-branch options>
#   See git filter-branch for additional option information.
#
#   <number>
#   Only the last <numbers> of commits are rewritten.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

ARGUMENTS=
REFLIST=
while [ "$1" != "" ]; do
    if [[ $1 =~ ^[0-9]+$ ]]; then
        REFLIST="HEAD~$1..HEAD"
    else
        ARGUMENTS="${ARGUMENTS} $1"
    fi
    shift
done

git filter-branch --env-filter 'export GIT_COMMITTER_DATE=$GIT_AUTHOR_DATE; export GIT_COMMITTER_NAME=$GIT_AUTHOR_NAME; export GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL;' ${ARGUMENTS} ${REFLIST}
git update-ref -d refs/original/refs/heads/master
