#!/bin/sh

#
# Copyright (c) 2017 Nicole Cordes, v1.0.1
#
# This script pulls all local branches with tracking information
#
#   git pull-all [-f | --force] [-l | --log]
#
#   -f | --force
#   Force the local branch to be hard reset to its tracking branch.
#
#   -l | --log
#   Show information about tracking branch and executed command.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

FORCE=false
LOG=false
while [ "$1" != "" ]; do
    case $1 in
        -f|--force )
            FORCE=true
            ;;
        -l|--log )
            LOG=true
            ;;
    esac
    shift
done

git branch -lvv | while read line ; do
    # Check for tracking remote branch
    # develop      40b68b8 [origin/develop] Merge branch 'hotfix/1.0.1' into develop
    if [[ "$line" =~ ([^*\ ]+)([^[]+\[)([^/]+)/([^\]:]+) ]]; then
        if $FORCE; then
            COMMAND="git checkout --quiet ${BASH_REMATCH[1]} && git fetch ${BASH_REMATCH[3]} && git reset --hard ${BASH_REMATCH[3]}/${BASH_REMATCH[4]} && git checkout --quiet -"
        else
            COMMAND="git checkout --quiet HEAD~1 && git fetch ${BASH_REMATCH[3]} ${BASH_REMATCH[1]}:${BASH_REMATCH[4]} && git checkout --quiet -"
        fi
        if $LOG; then
            echo ""
            echo "$line"
            echo "$COMMAND"
        fi
        eval $COMMAND
    fi
done
